name: image
on:
  push:
  workflow_dispatch:
  schedule:
        # Runs everyday at 8:00 AM
        - cron: "0 0 * * *"
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: namoscato/action-tinify@v1
        with:
          api_key: ${{ secrets.API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
